name: "Reusable upload to S3"

on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        required: true
      s3_bucket_name:
        type: string
        required: true
      s3_file_path:
        type: string
        required: true
    secrets:
      AWS_ACCOUNT_ID:
        required: true

env:
  AWS_ROLE_ARN: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}"

permissions:
  id-token: write
  contents: read

jobs:
  publish_lambda_layer:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: "Get file basename"
        id: file_basename
        run: |
          echo "BASENAME=$(basename ${{ inputs.s3_file_path }})" >> "$GITHUB_OUTPUT"

      - name: "Validate file basename"
        run: |
          if [[ ! ${{ steps.file_basename.outputs.BASENAME }} =~ ^[^/]+$ ]]; then
            echo "Error: Invalid file basename"
            exit 1
          fi

      - name: "Download artifact and to zip"
        uses: ./.github/actions/download-artifact-and-to-zip
        with:
          artifact_name: ${{ inputs.artifact_name }}
          zip_file_name: ${{ steps.file_basename.outputs.BASENAME }}

      - name: "Upload to S3"
        run: |
          aws s3 cp "${{ steps.file_basename.outputs.BASENAME }}" "s3://${{ inputs.s3_bucket_name }}/${{ inputs.s3_file_path }}"

